---
#
# EECS 5287: Principles of Cloud Computing
# Author: Morley Bankston
#
# This playbook starts our producer service

  - name: Run Kafka producer
    systemd:
      name: producer
      state: started
      daemon_reload: yes
    become: true
    become_user: root
...
