---
#
# EECS 5287: Principles of Cloud Computing
# Author: Morley Bankston
#
# This playbook will install some packages on VirtualBox VM1.2_R

  - name: "Update Ubuntu"
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600
      force_apt_get: yes
    become: yes
    become_user: root

  - name: Install or update pip
    apt:
      name: python3-pip
      state: latest
    become: yes
    become_user: root
    
  - name: Installing boto3 for AWS dependency
    pip:
      name: boto3

...
