  - name: "Check for conf file"
    stat:
      path: /etc/systemd/system/producer.service.d/producer.conf
    register: producer_conf
    
  - name: "Setup service conf file"
    ansible.builtin.lineinfile:
      path: /etc/systemd/system/producer.service.d/producer.conf
      line: "[Service]\nEnvironment=\"ZOOKEEPER_IP=129.114.25.15\""
      create: yes
    become: yes
    become_user: root
    when: not producer_conf.stat.exists
