---
#
# EECS 5287: Principles of Cloud Computing
# Author: Stephen Rees
#
# Modified by: Morley Bankston
#
# This playbook will setup Kafka on VirtualBox VM3_DB

  # - name: "Create a user for Kafka"
  #   ansible.builtin.user:
  #     name: kafka
  #     password: '$6$ePlwwMr.AKJOiu9U$EkclGDWSpRf.uc8CWJ9e4fday0V51pHFzoY51JsK6Q.U2vrikjU4peErVelENkenncFUcfciaVZn8pB0YMJ38.'
  #     groups: sudo
  #     state: present
  #   become: yes
  #   become_user: root
      
  # - name: "Download and expand Kafka"
  #   shell: 'mkdir -p ~/Downloads; curl "https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz" -o ~/Downloads/kafka.tgz; mkdir -p ~/kafka && cd ~/kafka; tar -xvzf ~/Downloads/kafka.tgz --strip 1'
  #   become: yes
  #   become_user: kafka

  - name: "Update Kafka Broker Id"
    ansible.builtin.lineinfile:
      path: /home/kafka/kafka/config/server.properties
      regexp: '^broker.id='
      line: broker.id=1
    become: yes
    become_user: root
  
  - name: "Update Kafka Advertised Listeners"
    ansible.builtin.lineinfile:
      path: /home/kafka/kafka/config/server.properties
      regexp: '^#advertised.listeners='
      line: "advertised.listeners=PLAINTEXT://{{ couch_ip }}:9092"
    become: yes
    become_user: root
    
  - name: "Create kafka service"
    copy:
      dest: /etc/systemd/system/kafka.service
      content: |
        [Unit]

        [Service]
        Type=simple
        User=kafka
        ExecStart=/bin/sh -c '/home/kafka/kafka/bin/kafka-server-start.sh /home/kafka/kafka/config/server.properties > /home/kafka/kafka/kafka.log 2>&1'
        ExecStop=/home/kafka/kafka/bin/kafka-server-stop.sh
        Restart=on-abnormal

        [Install]
        WantedBy=multi-user.target
    become: yes
    become_user: root
    
  - name: "Run Kafka"
    systemd:
      name: kafka
      state: started
      daemon_reload: yes
      enabled: yes
    become: true
    become_user: root
...
