version: "3.7"

services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 129.114.25.58
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 129.114.25.15:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://129.114.25.58:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      

  couchdb:
    image: bitnami/couchdb
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: 123456
      COUCHDB_CREATE_DATABASES: "yes"
    volumes:
      - ~/data:/opt/couchdb/data