---
  - name: Download kafka
    get_url:
      url: https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
      dest: /home/cc/kafka.tgz
      
  - name: Extract kafka
    unarchive:
      src: /home/cc/kafka.tgz
      dest: /home/cc/
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Config 1
    lineinfile:
      path: /home/cc/config/server.properties
      search_string: '#listeners=PLAINTEXT://:9092'
      line: listeners=PLAINTEXT://:9092
      
  - name: Config 2    
    lineinfile: 
      path: /home/cc/config/server.properties
      search_string: '#advertised.listeners=PLAINTEXT://your.host.name:9092'
      line: advertised.listeners=PLAINTEXT://localhost:9092
      
  - name: Config 3  
    lineinfile: 
      path: /home/cc/config/server.properties
      search_string: '#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL'
      line: listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
  
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
    become_user: root
    
  - name: Install default-jre
    apt:
      name: default-jre
      state: latest
    become: yes
    become_user: root

  - name: Install pip
    apt:
      name: python3-pip
      state: latest
    become: yes
    become_user: root
    
  - name: Installing kafka-python library
    pip:
      name: kafka-python
    become: yes
    become_user: root
    
  - name: Modify Firewall 1
    ansible.builtin.shell: sudo ufw limit 9092
  
  - name: Modify Firewall 2
    ansible.builtin.shell: sudo ufw limit 2128

  - name: Modify Firewall 3
    ansible.builtin.shell: sudo ufw limit 2181

  - name: Remove
    ansible.builtin.shell: rm -rf /tmp/zookeeper/ /tmp/kafka*
  
  - name: Run zookeeper
    ansible.builtin.shell: bin/zookeeper-server-start.sh config/zookeeper.properties
    async: 300
    poll: 0
    
  - name: Run broker
    ansible.builtin.shell: bin/kafka-server-start.sh config/server.properties
    async: 300
    poll: 0
    
...      