---
- name: Create cloud instances
  hosts: localhost
  tasks:
  - name: create keypair for VM
    openstack.cloud.keypair:
      cloud: openstack
      state: present
      name: Team7_Chameleon_SSH
      public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC65Z8pYBi7QGI0TSr0acjY5zCrjhZRr0BSke9Rivj1JUtMll4T/8HPcU4IiKk/OuO3RruNth/dayxOS/+pGbtG3TV0rXDJNM5njm62t4EUvR8ZBp7s+lRxAm/0/GSnFQt0/lpRb8FrDEatS2YHQzrsEYmIUPg7YRg3KtZRpVSy1YXsklOlAlgo2iaFgQDg71nVy3Vkkjmlx7jlK4U98c11yGILgV8qjasv4qHkVWbjUih9ImPxmV9SzYw4gavFB+4SzSmy28OILGE4eld+7SgdiJ8RjdRGr12bPLqMNVbh8xcRo7QIp21lgs31GdSK0eSg1fYG55hZMeXjSAdibNGd Generated-by-Nova
  - name: Create VM2 on Chameleon 
    openstack.cloud.server:
         state: present
         cloud: openstack
         name: Team7-VM2
         availability_zone: nova
         image: CC-Ubuntu20.04
         key_name: Team7_Chameleon_SSH
         timeout: 200
         flavor: m1.small
         network: CH-819381-net
         floating_ips:
           - 129.114.25.15
         security_groups:
           - 667273fd-a67a-4ca2-8a68-3088220e6374
           - 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
           - ENABLE_SSH
           - ENABLE_KAFKA_COUCHDB
  - name: Create VM3 on Chameleon 
    openstack.cloud.server:
         state: present
         cloud: openstack
         name: Team7-VM3
         availability_zone: nova
         image: CC-Ubuntu20.04
         key_name: Team7_Chameleon_SSH
         timeout: 200
         flavor: m1.small
         network: CH-819381-net
         floating_ips:
           - 129.114.25.58
         security_groups:
           - 667273fd-a67a-4ca2-8a68-3088220e6374
           - 7e09e9fd-4971-49bb-bd55-9aa2fa149b16
           - ENABLE_SSH
           - ENABLE_KAFKA_COUCHDB
...
