---
#
# EECS 5287: Principles of Cloud Computing
# Author: Stephen Rees
#
# This playbook will install some packages on VirtualBox VM2_ZK

  - name: Install services
    copy:
      src: /home/ubuntu/CS5287/PA2/VM2_ZK/consumer.service
      dest: /etc/systemd/system
      remote_src: yes
    become: yes
    become_user: root
...
