# EECS 5287: Principles of Cloud Computing
# Author: Stephen Rees
#
# This playbook will remove the two servers we provisioned on AWS and will be triggered by vagrant destroy of VM1.2
- name: "Destroy Cloud VMs"
  hosts: MyLocalVMs	         # specified in the MyInventory file
  remote_user:  vagrant      # vagrant provisioned virtual box has user of vagrant
  gather_facts: yes          # We ask Ansible to collect all facts
  become_user: no            # We will become on individual tasks as needed

  tasks:    # the task to be performed (here I am showing the effect of include_)
  - name: Remove ZK instance on AWS
    amazon.aws.ec2_instance:
      region: us-east-1
      filters:
        instance-state-name: running
        "tag:Name": ansible-zookeeper
      state: absent
  - name: Remove Couch instance on AWS
    amazon.aws.ec2_instance:
      region: us-east-1
      filters:
        instance-state-name: running
        "tag:Name": ansible-couchdb
      state: absent
