---
  - name: Remove any previously install docker package
    apt:
      name: docker
      state: absent
    become: yes
    become_user: root

  - name: Install Docker dependencies
    apt:
      name: "{{packages}}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    become: yes
    become_user: root

  - name: Add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes
    become_user: root
  
  - name: Add docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
    become: yes
    become_user: root
  
  - name: Install docker
    apt:
      name: "{{packages}}"
      state: latest
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    become: yes
    become_user: root

  # this already seems to be updated, may not be necessary
  - name: Modify docker service
    ansible.builtin.lineinfile:
      path: /lib/systemd/system/docker.service
      regexp: '^ExecStart='
      line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd"
    become: yes
    become_user: root
  
  - name: Ensure docker service has been restarted
    ansible.builtin.systemd:
      state: started
      daemon_reload: yes
      name: docker
    become: yes
    become_user: root
  
  - name: checking docker service status
    command: systemctl status docker
    register: docker_status

  - name: showing docker status
    debug:
      var: docker_status
