---   
  - name: Copy join command from Vagrant to the worker node.
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777
    become: yes
    become_user: root

  - name: Join the Worker nodes to the cluster.
    become: yes
    become_user: root
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not
...
